Repository qri-io/startf, pull requests merged in 2018-11, with the labels that each got.

#22 feat(MutateCheck): add option for dataset mutation checks, rename ExecFile -> ExecScript
  ds/dataset.go
  ds/dataset_test.go
  transform.go
  transform_test.go
Labels: in progress

#23 chore(release): release version 0.1.0
  ds/dataset.go
  startf.go
  transform.go
Labels: in progress

#24 chore(starlark): Complete move to new starlark name and import path.
  .circleci/config.yml
  README.md
  context/context.go
  context/context_test.go
  ds/dataset.go
  ds/dataset_test.go
  ds/entry_reader.go
  ds/entry_reader_test.go
  ds/entry_writer.go
  entry_reader.go
  entry_reader_test.go
  qri/entry_writer.go
  qri/qri.go
  qri/qri_test.go
  transform.go
  transform_test.go
Labels: in progress

#25 docs(readme): update readme
  README.md
Labels: docs, in progress

#26 chore(gx): update gx deps for go-ipfs 0.4.18
  package.json
Labels: chore, in progress
